# Node Port Service For JavaApp
apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: java-app
	
---
# Replication Controller for javaApp
apiVersion: v1
kind: ReplicationController
metadata:
  name: java-app-controller
spec:
  replicas: 2
  selector:
    app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - image: mhali/java_app
        name: java-app
        ports:
        - containerPort: 8080  